import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('PostgreSQL RLS isolates conversations, protects receipts and storage, and honors blocking',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth,storage to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;
 grant select,insert,delete on storage.objects to authenticated;
 create function storage.foldername(name text) returns text[] language sql as $$select string_to_array(name,'/')$$;`);
 await db.exec(await readFile(new URL('../supabase/INSTALL.sql',import.meta.url),'utf8'));
 const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002',c='00000000-0000-0000-0000-000000000003';
 await db.exec(`insert into auth.users values('${a}'),('${b}'),('${c}')`);
 async function as(id){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false)`);}
 await as(a);let out=await db.query(`select public.open_thread('${b}') as t`);const t=out.rows[0].t.id;
 await db.exec(`insert into messages(thread_id,sender_id,kind,body) values('${t}','${a}','text','secret')`);
 await assert.rejects(db.exec(`update messages set body='forged'`));
 await assert.rejects(db.exec(`insert into messages(thread_id,sender_id,kind,body,read_at) values('${t}','${a}','text','fake receipt',now())`));
 await db.exec(`insert into storage.objects(bucket_id,name) values('chat-media','${t}/${a}/photo.jpg')`);
 await as(c);assert.equal((await db.query('select * from messages')).rows.length,0);assert.equal((await db.query('select * from threads')).rows.length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await assert.rejects(db.exec(`insert into messages(thread_id,sender_id,kind,body) values('${t}','${c}','text','intrusion')`));
 await as(b);assert.equal((await db.query('select * from messages')).rows.length,1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 await db.exec(`update messages set read_at=now()`);assert.ok((await db.query('select read_at from messages')).rows[0].read_at);
 await db.exec(`insert into blocks(user_id,blocked_id) values('${b}','${a}')`);
 assert.equal((await db.query('select * from messages')).rows.length,0);
 await as(a);await assert.rejects(db.exec(`select public.open_thread('${b}')`));assert.equal((await db.query('select * from storage.objects')).rows.length,0);
 await db.exec(`reset role;set role anon`);await assert.rejects(db.query('select * from profiles'));
 await db.close();
});
