import {JSDOM,VirtualConsole} from 'jsdom';
import {indexedDB,IDBKeyRange} from 'fake-indexeddb';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation'))errors.push(e.message);});
const dom=new JSDOM('<!doctype html><html><head><meta name="theme-color" content="#fff"></head><body><div id="root"></div></body></html>',{url:'https://prisme.test/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window;Object.defineProperty(w,'indexedDB',{value:indexedDB});w.IDBKeyRange=IDBKeyRange;w.fetch=async()=>({ok:true,json:async()=>({supabaseUrl:'',supabaseAnonKey:''})});w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.IntersectionObserver=class{observe(){}disconnect(){}};w.confirm=()=>true;w.prompt=()=>null;w.HTMLElement.prototype.scrollTo=function(v){this.scrollLeft=v.left||0;this.scrollTop=v.top||0;this.dispatchEvent(new w.Event('scroll'));};w.HTMLElement.prototype.scrollBy=function(v){this.scrollTo({left:this.scrollLeft+(v.left||0),top:this.scrollTop+(v.top||0)});};w.URL.createObjectURL=()=> 'blob:demo';w.URL.revokeObjectURL=()=>{};
const bundle=(await readdir(new URL('../dist/assets',import.meta.url))).find(n=>n.startsWith('index-')&&n.endsWith('.js'));const js=await readFile(new URL('../dist/assets/'+bundle,import.meta.url),'utf8');w.eval(js.replace(/export\{[^}]+\};?\s*$/,''));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<80;i++){if(fn())return;await sleep(25);}throw new Error('UI timeout: '+w.document.body.textContent.slice(-1200));}
function button(text){return [...w.document.querySelectorAll('button')].find(b=>b.textContent.trim()===text||b.getAttribute('aria-label')===text);}
async function click(text){await until(()=>button(text));button(text).click();await sleep(80);}
function input(selector,value){const e=w.document.querySelector(selector);assert.ok(e,selector);const proto=e.tagName==='TEXTAREA'?w.HTMLTextAreaElement.prototype:w.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,value);e.dispatchEvent(new w.Event('input',{bubbles:true}));e.dispatchEvent(new w.Event('change',{bubbles:true}));}
await click('Essayer la démonstration');await until(()=>w.document.querySelectorAll('.post-card').length===3);assert.ok(w.document.body.textContent.includes('DÉMONSTRATION'));
await click('J’aime');await until(()=>button('Retirer le J’aime'));
await click('Enregistrer');await until(()=>button('Retirer des favoris'));
await click('Commentaires');input('input[aria-label="Ton commentaire"]','Très belle photo !');await sleep(30);await click('Envoyer le commentaire');await until(()=>w.document.body.textContent.includes('Très belle photo !'));await click('Fermer les commentaires');
await click('Plein écran');assert.equal(w.document.querySelectorAll('.viewer-page').length,3);await click('Fermer le plein écran');
await click('Chat');await until(()=>w.document.querySelector('.chat-person'));w.document.querySelector('.chat-person').click();await sleep(100);input('input[aria-label="Envoyer un Chat"]','Bonjour depuis Prisme');await sleep(30);await click('Envoyer le message');await until(()=>w.document.querySelector('.chat-message')?.textContent.includes('Bonjour depuis Prisme'));
await click('Retour aux chats');await click('Profil');await click('Paramètres');await click('Sombre');assert.equal(w.document.documentElement.dataset.theme,'dark');await click('Retour');await click('Modifier le profil');const name=w.document.querySelector('.page-form input[maxlength="60"]');Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set.call(name,'Alex Test');name.dispatchEvent(new w.Event('input',{bubbles:true}));await sleep(30);await click('Enregistrer');await until(()=>w.document.body.textContent.includes('Alex Test'));
await click('Publier');await click('Lien / Embed');input('.composer textarea','https://www.youtube.com/watch?v=dQw4w9WgXcQ');await sleep(30);await click('Publier');await until(()=>!w.document.querySelector('.composer'));await click('Accueil');await until(()=>w.document.querySelectorAll('.post-card').length===4);
await click('Publier');
const picker=w.document.querySelector('.file-pick input');Object.defineProperty(picker,'files',{value:[new w.File(['photo-one'],'one.png',{type:'image/png'}),new w.File(['photo-two'],'two.png',{type:'image/png'})]});picker.dispatchEvent(new w.Event('change',{bubbles:true}));await sleep(70);await click('Publier');await until(()=>!w.document.querySelector('.composer'));await until(()=>w.document.querySelectorAll('.post-card').length===5);assert.ok(w.document.querySelector('.post-card .media-counter').textContent.includes('1/2'));
await click('Chat');await until(()=>w.document.querySelector('.chat-person'));w.document.querySelector('.chat-person').click();await until(()=>w.document.querySelector('.chat-message')?.textContent.includes('Bonjour depuis Prisme'));
assert.deepEqual(errors,[]);console.log('PASS: demo login, feed, likes, saves, comments, fullscreen, chat send, theme, profile edit, embed publish, 2-photo upload, message persistence.');dom.window.close();
