import {createClient, type SupabaseClient} from '@supabase/supabase-js';
import type {Profile,Post,Comment,Thread,Message,Config} from './types';
import {cleanUsername,validUsername,safeUrl} from './logic.mjs';
export let client:SupabaseClient|null=null;
export let demo=false;
export let uid='';
let cfg:Config={supabaseUrl:'',supabaseAnonKey:''};
const signed=new Map<string,{url:string;until:number}>();
export const meDemo:Profile={id:'demo-me',username:'alex.world',name:'Alex',bio:'Les belles rencontres et les petits moments. 🏳️‍🌈\nMarseille, France',avatar:'/photos/avatar.jpg',website:''};
type DB={profiles:Profile[];posts:Post[];comments:Comment[];messages:Message[];threads:Thread[];follows:string[];blocks:string[]};
let db:DB;
function openDB():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open('prisme-demo',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function save(){const d=await openDB();await new Promise<void>((resolve,reject)=>{const t=d.transaction('state','readwrite');t.objectStore('state').put(db,'data');t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);});d.close();}
function seed():DB{
 const cam:Profile={id:'demo-cam',username:'camille.m',name:'Camille',bio:'De la lumière, la mer et des rencontres. ☀️',avatar:'/photos/camille.jpg'};
 const leo:Profile={id:'demo-leo',username:'leo.voyage',name:'Léo',bio:'Toujours dehors. 📷',avatar:'/photos/leo.jpg'};
 const now=Date.now(); const posts:Post[]=[{id:'sample-1',user_id:cam.id,caption:'Le bonheur, c’est parfois juste une fin de journée au bord de l’eau. 🌊 #marseille #voyage',media:[{type:'image',url:'/photos/coast.jpg'},{type:'image',url:'/photos/city.jpg'},{type:'image',url:'/photos/cafe.jpg'}],created_at:new Date(now-3600000).toISOString(),owner:cam,likes:[{user_id:leo.id}],saves:[],comments:[]},{id:'sample-2',user_id:leo.id,caption:'Prendre le temps. #nature #weekend',media:[{type:'image',url:'/photos/mountain.jpg'}],created_at:new Date(now-7200000).toISOString(),owner:leo,likes:[],saves:[],comments:[]},{id:'sample-3',user_id:meDemo.id,caption:'Un nouveau départ, toutes nos couleurs. 🏳️‍🌈 #theworldisyour',media:[{type:'image',url:'/photos/city.jpg'},{type:'image',url:'/photos/coast.jpg'}],created_at:new Date(now-10800000).toISOString(),owner:meDemo,likes:[{user_id:cam.id}],saves:[],comments:[]}];
 return {profiles:[meDemo,cam,leo],posts,comments:[],messages:[],threads:[{id:'demo-thread',user_a:meDemo.id,user_b:cam.id,peer:cam,created_at:new Date(now).toISOString(),unread:0}],follows:[cam.id],blocks:[]};
}
export async function init(){cfg=JSON.parse(localStorage.getItem('prisme-config')||'null')||await fetch('/config.json').then(r=>r.json()).catch(()=>cfg);if(cfg.supabaseUrl&&cfg.supabaseAnonKey)client=createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);return cfg;}
export function configured(){return !!client;}
export function setConfig(value:Config){const u=new URL(value.supabaseUrl);if(u.protocol!=='https:'||!u.hostname.endsWith('.supabase.co'))throw new Error('Utilise l’URL HTTPS de ton projet Supabase (.supabase.co).');let role='';try{role=JSON.parse(atob(value.supabaseAnonKey.split('.')[1])).role;}catch{}if(value.supabaseAnonKey.startsWith('sb_secret_')||role==='service_role')throw new Error('Clé secrète refusée. Utilise seulement la clé publique publishable ou anon.');if(!value.supabaseAnonKey.startsWith('sb_publishable_')&&role!=='anon')throw new Error('Clé publique Supabase invalide.');localStorage.setItem('prisme-config',JSON.stringify(value));location.reload();}
export async function startDemo(){demo=true;uid=meDemo.id;const d=await openDB();db=await new Promise<DB>((resolve)=>{const r=d.transaction('state').objectStore('state').get('data');r.onsuccess=()=>resolve(r.result||seed());r.onerror=()=>resolve(seed());});d.close();await save();return profile(uid);}
export async function session(){if(!client)return null;const {data,error}=await client.auth.getSession();if(error)throw error;uid=data.session?.user.id||'';return data.session;}
export async function login(email:string,password:string){const {data,error}=await client!.auth.signInWithPassword({email,password});if(error)throw error;uid=data.user.id;return profile(uid);}
export async function signup(email:string,password:string){const {data,error}=await client!.auth.signUp({email,password,options:{emailRedirectTo:'fr.prisme.social://auth'}});if(error)throw error;if(!data.session)return null;uid=data.user!.id;return profile(uid);}
export async function logout(){if(client&&!demo)await client.auth.signOut();demo=false;uid='';signed.clear();}
export async function profile(id:string):Promise<Profile>{if(demo)return db.profiles.find(p=>p.id===id)!;const {data,error}=await client!.from('profiles').select('*').eq('id',id).single();if(error)throw error;return data;}
export async function updateProfile(p:Profile){p={...p,username:cleanUsername(p.username)};if(p.website&&!safeUrl(p.website))throw new Error('Le lien du profil doit commencer par https://.');if(!validUsername(p.username))throw new Error('Pseudo : 3 à 24 caractères, lettres sans accents, chiffres, points ou _.');if(demo){db.profiles=db.profiles.map(x=>x.id===uid?p:x);db.posts=db.posts.map(x=>x.user_id===uid?{...x,owner:p}:x);await save();return p;}const {error}=await client!.from('profiles').update({username:p.username,name:p.name,bio:p.bio,avatar:p.avatar,website:p.website||''}).eq('id',uid);if(error)throw error;return p;}
export async function posts(offset=0,limit=30):Promise<Post[]>{if(demo)return db.posts.filter(p=>!db.blocks.includes(p.user_id)).slice(offset,offset+limit);const {data,error}=await client!.from('posts').select('*,owner:profiles!posts_user_id_fkey(*),likes(user_id),saves(user_id),comments(id)').order('created_at',{ascending:false}).range(offset,offset+limit-1);if(error)throw error;return data as Post[];}
export async function addPost(caption:string,media:Post['media']){if(demo){db.posts.unshift({id:crypto.randomUUID(),user_id:uid,caption,media,created_at:new Date().toISOString(),owner:await profile(uid),likes:[],saves:[],comments:[]});await save();return;}const {error}=await client!.from('posts').insert({user_id:uid,caption,media});if(error)throw error;}
export async function removePost(id:string){if(demo){db.posts=db.posts.filter(p=>p.id!==id||p.user_id!==uid);await save();return;}const {error}=await client!.from('posts').delete().eq('id',id).eq('user_id',uid);if(error)throw error;}
export async function toggle(table:'likes'|'saves',post:Post){const exists=post[table].some(l=>l.user_id===uid);if(demo){const p=db.posts.find(x=>x.id===post.id)!;p[table]=exists?p[table].filter(l=>l.user_id!==uid):[...p[table],{user_id:uid}];await save();return;}const q=client!.from(table);const {error}=exists?await q.delete().eq('user_id',uid).eq('post_id',post.id):await q.insert({post_id:post.id,user_id:uid});if(error)throw error;}
export async function getComments(post_id:string):Promise<Comment[]>{if(demo)return db.comments.filter(c=>c.post_id===post_id);const {data,error}=await client!.from('comments').select('*,owner:profiles!comments_user_id_fkey(*)').eq('post_id',post_id).order('created_at').limit(200);if(error)throw error;return data;}
export async function comment(post_id:string,body:string){if(demo){const c={id:crypto.randomUUID(),post_id,user_id:uid,body,owner:await profile(uid),created_at:new Date().toISOString()};db.comments.push(c);db.posts.find(p=>p.id===post_id)?.comments.push({id:c.id});await save();return;}const {error}=await client!.from('comments').insert({post_id,user_id:uid,body});if(error)throw error;}
export async function people(q=''):Promise<Profile[]>{if(demo)return db.profiles.filter(p=>p.id!==uid&&!db.blocks.includes(p.id)&&(p.username+' '+p.name).toLowerCase().includes(q.toLowerCase()));let r=client!.from('profiles').select('*').neq('id',uid).limit(40);if(q)r=r.ilike('username','%'+q.replace(/[^\p{L}\p{N}_.]/gu,'')+'%');const {data,error}=await r;if(error)throw error;return data;}
export async function following():Promise<string[]>{if(demo)return db.follows;const {data,error}=await client!.from('follows').select('following_id').eq('follower_id',uid);if(error)throw error;return data.map(x=>x.following_id);}
export async function follow(id:string){const follows=await following();if(demo){db.follows=follows.includes(id)?follows.filter(x=>x!==id):[...follows,id];await save();return;}const {error}=follows.includes(id)?await client!.from('follows').delete().eq('follower_id',uid).eq('following_id',id):await client!.from('follows').insert({follower_id:uid,following_id:id});if(error)throw error;}
export async function stats(id:string){if(demo)return {posts:db.posts.filter(p=>p.user_id===id).length,followers:id===uid?0:db.follows.includes(id)?1:0,following:id===uid?db.follows.length:0};const count=async(table:string,column:string)=>{const {count,error}=await client!.from(table).select('*',{count:'exact',head:true}).eq(column,id);if(error)throw error;return count||0;};const [p,f,g]=await Promise.all([count('posts','user_id'),count('follows','following_id'),count('follows','follower_id')]);return {posts:p,followers:f,following:g};}
export async function openThread(peer:Profile):Promise<Thread>{if(demo){let t=db.threads.find(t=>t.peer.id===peer.id);if(!t){t={id:crypto.randomUUID(),user_a:uid,user_b:peer.id,peer,created_at:new Date().toISOString(),unread:0};db.threads.push(t);await save();}return t;}const {data,error}=await client!.rpc('open_thread',{peer_id:peer.id});if(error)throw error;return {...data,peer,unread:0};}
export async function threads():Promise<Thread[]>{if(demo)return db.threads.filter(t=>!db.blocks.includes(t.peer.id)).map(t=>({...t,last:db.messages.filter(m=>m.thread_id===t.id).at(-1)}));const {data,error}=await client!.rpc('inbox');if(error)throw error;return data||[];}
async function mediaUrl(path:string){if(!path)return '';if(demo)return path;const found=signed.get(path);if(found&&found.until>Date.now())return found.url;const {data,error}=await client!.storage.from('chat-media').createSignedUrl(path,3600);if(error)throw error;signed.set(path,{url:data.signedUrl,until:Date.now()+3000000});return data.signedUrl;}
export async function messages(thread_id:string):Promise<Message[]>{if(demo)return db.messages.filter(m=>m.thread_id===thread_id).map(m=>({...m,url:m.media_path}));const {data,error}=await client!.from('messages').select('*').eq('thread_id',thread_id).order('created_at',{ascending:false}).limit(200);if(error)throw error;return Promise.all(data.reverse().map(async m=>({...m,url:await mediaUrl(m.media_path)})));}
export async function markRead(thread_id:string){if(demo)return;const {error}=await client!.from('messages').update({read_at:new Date().toISOString()}).eq('thread_id',thread_id).neq('sender_id',uid).is('read_at',null);if(error)throw error;}
export async function send(thread_id:string,kind:Message['kind'],body='',media_path=''){if(demo){db.messages.push({id:crypto.randomUUID(),thread_id,sender_id:uid,kind,body,media_path,created_at:new Date().toISOString(),read_at:null});await save();return;}const {error}=await client!.from('messages').insert({thread_id,sender_id:uid,kind,body,media_path});if(error)throw error;}
export async function upload(file:File,progress:(n:number)=>void,thread?:string):Promise<string>{if(file.size>50*1024*1024)throw new Error('Ce fichier dépasse 50 Mo. Choisis une version plus légère.');if(!/^(image\/(jpeg|png|webp|gif)|video\/(mp4|webm|quicktime)|audio\/(webm|ogg|mp4|mpeg|wav))/.test(file.type))throw new Error('Format non pris en charge. Utilise une photo JPG/PNG/WebP, une vidéo MP4/WebM ou un audio.');if(demo){const result=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result as string);r.onerror=()=>reject(r.error);r.readAsDataURL(file);});progress(100);return result;}const ext=file.name.split('.').pop()?.replace(/[^a-z0-9]/gi,'').slice(0,8)||'bin';const path=(thread?thread+'/':'')+uid+'/'+crypto.randomUUID()+'.'+ext;const bucket=thread?'chat-media':'media';const {data:{session},error}=await client!.auth.getSession();if(error||!session)throw error||new Error('Reconnecte-toi pour publier.');await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST',cfg.supabaseUrl+'/storage/v1/object/'+bucket+'/'+path);x.setRequestHeader('Authorization','Bearer '+session.access_token);x.setRequestHeader('apikey',cfg.supabaseAnonKey);x.setRequestHeader('Content-Type',file.type.split(';')[0]);x.timeout=180000;x.upload.onprogress=e=>e.lengthComputable&&progress(Math.round(e.loaded/e.total*100));x.onload=()=>x.status<300?resolve():reject(new Error('Transfert refusé ('+x.status+'). Vérifie le stockage et ses règles.'));x.onerror=()=>reject(new Error('Connexion interrompue pendant le transfert.'));x.ontimeout=()=>reject(new Error('Le transfert a pris trop de temps. Réessaie.'));x.send(file);});return thread?path:client!.storage.from(bucket).getPublicUrl(path).data.publicUrl;}
export async function block(id:string){if(demo){db.blocks.push(id);await save();return;}const {error}=await client!.from('blocks').insert({user_id:uid,blocked_id:id});if(error&&error.code!=='23505')throw error;}
export async function report(post_id:string,reason:string){if(demo)return;const {error}=await client!.from('reports').insert({user_id:uid,post_id,reason});if(error)throw error;}

export async function profilePosts(id:string,saved=false,offset=0):Promise<Post[]>{if(demo)return db.posts.filter(p=>saved?p.saves.some(x=>x.user_id===uid):p.user_id===id).slice(offset,offset+30);let q=client!.from('posts').select('*,owner:profiles!posts_user_id_fkey(*),likes(user_id),saves'+(saved?'!inner':'')+'(user_id),comments(id)').order('created_at',{ascending:false}).range(offset,offset+29);q=saved?q.eq('saves.user_id',uid):q.eq('user_id',id);const {data,error}=await q;if(error)throw error;return data as unknown as Post[];}
