import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ChevronLeft,ChevronRight,Volume2,VolumeX,Play,ExternalLink,X,Heart,MessageCircle,Send,Bookmark,MoreHorizontal,Flag,Trash2,UserX,Link,Camera} from 'lucide-react';
import type {Profile,Post,Media} from './types';
import {useApp} from './context';
import * as api from './api';
import {safeUrl} from './logic.mjs';
export function IconButton({label,onClick,children,className='',disabled=false}:{label:string;onClick?:()=>void;children:ReactNode;className?:string;disabled?:boolean}){return <button type="button" className={'icon-btn '+className} aria-label={label} title={label} onClick={onClick} disabled={disabled}>{children}</button>;}
export function Avatar({person,size='normal',ring=false,onClick}:{person:Profile;size?:string;ring?:boolean;onClick?:()=>void}){const cls='avatar '+size+(ring?' ring':'');const content=person.avatar?<img src={person.avatar} alt="" onError={e=>{e.currentTarget.style.display='none';}}/>:<span>{(person.name||person.username||'?').slice(0,1).toUpperCase()}</span>;return onClick?<button type="button" aria-label={'Profil de '+(person.name||person.username)} className={cls} onClick={onClick}>{content}</button>:<span className={cls}>{content}</span>;}
export function Empty({title,children,icon}:{title:string;children?:ReactNode;icon?:ReactNode}){return <div className="empty"><div className="empty-icon">{icon||<Camera size={30}/>}</div><h2>{title}</h2><p>{children}</p></div>;}
export function BackHeader({title,children}:{title:string;children?:ReactNode}){const a=useApp();return <header className="page-header"><IconButton label="Retour" onClick={a.back}><ChevronLeft/></IconButton><h1>{title}</h1>{children||<span className="header-spacer"/>}</header>;}
export function When({date}:{date:string}){const diff=Date.now()-Date.parse(date);return <time dateTime={date}>{diff<60000?'À l’instant':diff<3600000?Math.floor(diff/60000)+' min':diff<86400000?Math.floor(diff/3600000)+' h':new Date(date).toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}</time>;}
export function Caption({text}:{text:string}){const a=useApp();return <>{text.split(/(#[\p{L}\p{N}_]+)/gu).map((t,i)=>t.startsWith('#')?<button className="hashtag" key={i} onClick={()=>{sessionStorage.setItem('prisme-search',t);a.push({name:'explore'});}}>{t}</button>:t)}</>;}
export function MediaCarousel({media,active=true,full=false,onOpen,onLike}:{media:Media[];active?:boolean;full?:boolean;onOpen?:()=>void;onLike?:()=>void}){
 const ref=useRef<HTMLDivElement>(null);const [index,setIndex]=useState(0);const lastTap=useRef(0);const moved=useRef(false);const start=useRef({x:0,y:0});
 function tap(){if(moved.current)return;const now=Date.now();if(now-lastTap.current<300){onLike?.();lastTap.current=0;}else{lastTap.current=now;}}
 return <div className={'media-wrap '+(full?'full':'')}><div className="carousel" ref={ref} onScroll={()=>{const el=ref.current!;setIndex(Math.round(el.scrollLeft/el.clientWidth));}} onTouchStart={e=>{start.current={x:e.touches[0].clientX,y:e.touches[0].clientY};moved.current=false;}} onTouchMove={e=>{if(Math.abs(e.touches[0].clientX-start.current.x)>8||Math.abs(e.touches[0].clientY-start.current.y)>8)moved.current=true;}} onClick={tap}>
 {media.map((m,i)=><div className="slide" key={i}><MediaItem media={m} active={active&&i===index} full={full}/></div>)}
 </div>{media.length>1&&<><span className="media-counter">{index+1}/{media.length}</span><div className="dots">{media.map((_,i)=><button key={i} aria-label={'Photo '+(i+1)} className={i===index?'selected':''} onClick={()=>ref.current?.scrollTo({left:i*ref.current.clientWidth,behavior:'smooth'})}/>)}</div><div className="carousel-arrows"><IconButton label="Photo précédente" disabled={index===0} onClick={()=>ref.current?.scrollBy({left:-ref.current.clientWidth,behavior:'smooth'})}><ChevronLeft/></IconButton><IconButton label="Photo suivante" disabled={index===media.length-1} onClick={()=>ref.current?.scrollBy({left:ref.current.clientWidth,behavior:'smooth'})}><ChevronRight/></IconButton></div></>}{onOpen&&<button className="open-media" onClick={e=>{e.stopPropagation();onOpen();}}><Play size={13}/> Plein écran</button>}</div>;
}
function MediaItem({media:m,active,full}:{media:Media;active:boolean;full:boolean}){
 const video=useRef<HTMLVideoElement>(null);const holder=useRef<HTMLDivElement>(null);const [visible,setVisible]=useState(false);const [muted,setMuted]=useState(true);const [playingEmbed,setPlayingEmbed]=useState(false);const [failed,setFailed]=useState(false);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>setVisible(entries[0].intersectionRatio>.65),{threshold:[0,.65,1]});if(holder.current)observer.observe(holder.current);return ()=>observer.disconnect();},[]);
 useEffect(()=>{const v=video.current;if(v){if(active&&visible&&!document.hidden)v.play().catch(()=>{});else v.pause();}if(!active||!visible)setPlayingEmbed(false);},[active,visible]);
 useEffect(()=>{const pause=()=>{if(document.hidden)video.current?.pause();};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[]);
 return <div ref={holder} className="media-item">{failed?<div className="media-failed">Média indisponible<small>Le lien est peut-être expiré.</small></div>:m.type==='image'?<img src={m.url} alt="Publication" loading={full?'eager':'lazy'} draggable={false} onError={()=>setFailed(true)}/>:m.type==='video'?<><video ref={video} src={m.url} poster={m.poster} loop muted={muted} playsInline preload="metadata" controls={full} onError={()=>setFailed(true)}/><IconButton label={muted?'Activer le son':'Couper le son'} className="sound" onClick={()=>setMuted(!muted)}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</IconButton></>:playingEmbed&&active?<iframe title="Lecteur intégré" src={m.url} sandbox="allow-scripts allow-same-origin allow-presentation" allow="autoplay; encrypted-media; fullscreen; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<button className="embed-preview" onClick={()=>setPlayingEmbed(true)}>{m.poster&&<img src={m.poster} alt=""/>}<span><Play/>Lire la vidéo intégrée</span><small>Lecture fournie par le site d’origine</small></button>}</div>;
}
export function PostActions({post,compact=false}:{post:Post;compact?:boolean}){const a=useApp();const liked=post.likes.some(l=>l.user_id===api.uid),saved=post.saves.some(l=>l.user_id===api.uid);return <div className={'post-actions '+(compact?'vertical':'')}><IconButton label={liked?'Retirer le J’aime':'J’aime'} className={liked?'liked':''} onClick={()=>a.run(async()=>{await api.toggle('likes',post);await a.refresh();})}><Heart fill={liked?'currentColor':'none'}/>{compact&&<small>{post.likes.length}</small>}</IconButton><IconButton label="Commentaires" onClick={()=>a.comments(post)}><MessageCircle/>{compact&&<small>{post.comments.length}</small>}</IconButton><IconButton label="Partager" onClick={()=>a.run(async()=>{const link=post.media[0]?.url;if(!link||!safeUrl(link)){a.notify('Cette publication de démonstration reste sur cet appareil.');return;}if(navigator.share)await navigator.share({title:'the World IS your',text:post.caption,url:link});else{await navigator.clipboard.writeText(link);a.notify('Lien copié.');}})}><Send/></IconButton><IconButton label={saved?'Retirer des favoris':'Enregistrer'} className={'save '+(saved?'saved':'')} onClick={()=>a.run(async()=>{await api.toggle('saves',post);await a.refresh();})}><Bookmark fill={saved?'currentColor':'none'}/></IconButton></div>;}
export function PostMenu({post}:{post:Post}){const a=useApp();const [open,setOpen]=useState(false);return <div className="post-menu"><IconButton label="Options de la publication" onClick={()=>setOpen(!open)}><MoreHorizontal/></IconButton>{open&&<><button className="menu-scrim" aria-label="Fermer les options" onClick={()=>setOpen(false)}/><div className="menu-pop">{post.user_id===api.uid?<button onClick={()=>{setOpen(false);if(confirm('Supprimer définitivement cette publication ?'))a.run(async()=>{await api.removePost(post.id);await a.refresh();});}}><Trash2/>Supprimer</button>:<><button onClick={()=>{setOpen(false);const reason=prompt('Pourquoi signaler cette publication ?');if(reason?.trim())a.run(async()=>{await api.report(post.id,reason);a.notify('Signalement envoyé.');});}}><Flag/>Signaler</button><button onClick={()=>{setOpen(false);if(confirm('Bloquer ce compte ?'))a.run(async()=>{await api.block(post.user_id);await a.refresh();});}}><UserX/>Bloquer ce compte</button></>}</div></>}</div>;}
export function PostCard({post,active,onOpen}:{post:Post;active:boolean;onOpen:()=>void}){const a=useApp();return <article className="post-card"><div className="post-heading"><Avatar person={post.owner} onClick={()=>a.push({name:'profile',person:post.owner})}/><button className="identity" onClick={()=>a.push({name:'profile',person:post.owner})}><strong>{post.owner.username}</strong><small><When date={post.created_at}/></small></button>{post.user_id!==api.uid&&!a.followed.includes(post.user_id)&&<button className="text-button" onClick={()=>a.run(async()=>{await api.follow(post.user_id);await a.refresh();})}>Suivre</button>}<PostMenu post={post}/></div><MediaCarousel media={post.media} active={active} onOpen={onOpen} onLike={()=>{if(!post.likes.some(l=>l.user_id===api.uid))a.run(async()=>{await api.toggle('likes',post);await a.refresh();});}}/><PostActions post={post}/><div className="post-copy"><strong>{post.likes.length} J’aime</strong><p><b>{post.owner.username}</b> <Caption text={post.caption}/></p><button className="muted" onClick={()=>a.comments(post)}>{post.comments.length?`Voir les ${post.comments.length} commentaires`:'Ajouter un commentaire…'}</button></div></article>;}
